# Generated by Django 5.1.4 on 2024-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
