# Generated by Django 5.1.4 on 2025-01-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='is_reported',
        ),
        migrations.AddField(
            model_name='link',
            name='report_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
