# Generated by Django 5.1.4 on 2025-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_remove_link_report_count_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
